language: go

go:
  - 1.13.x
  - master

services:
  - docker

before_install:
  - docker build -t xushikuan/remind-backend .
  - docker tag xushikuan/remind-backend:latest xushikuan/remind-backend:1.4
  - docker push xushikuan/remind-backend:1.4
