language: go

go:
  - 1.13.x

branches: # build only on these branches
  only:
    - master

jobs:
  include:
    - stage: build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t $DOCKER_USERNAME/$PROJECT_NAME .
        - docker tag $DOCKER_USERNAME/$PROJECT_NAME:latest $DOCKER_USERNAME/$PROJECT_NAME:1.4
        - docker push $DOCKER_USERNAME/$PROJECT_NAME:1.4

after_success:
  - bash <(curl -s https://codecov.io/bash)