version: '3.4'

services:
  remind-backend:
    image: xushikuan/remind-backend:${APPLICATION_VERSION}
    environment:
      - env=production
    env_file:
      - ./sillyhat-env-config/config.env
    ports:
      - 8803:8080
    deploy:
      replicas: 1
      restart_policy:
        max_attempts: 1